### ISSUE TITLE
Create project skeleton

### ISSUE THREAD

**Issue by bzz** [src-d/gitbase-playground#1]
Update project structure with the setup used for applicastion

 - [ ] FE: a `package.json` \w standard scripts that do `echo 1`
 - [x] BE: Empty test. Almost the same code structure as in CAT (use chi, but a separate dir for FE)
 - [x] Build structure, single binary
 - [x] TravisCI

**Comment by bzz** [comment]
> moved this from backlog to In Progress in Applications 10 days ago

do you think I would be a good time to start submitting the work you has done on this as PRs?  Do not need to be complete, etc

**Comment by dpordomingo** [comment]
Yes, I'm doing it right now :dagger:

**Comment by dpordomingo** [comment]
The first subtask is being addressed by https://github.com/src-d/gitbase-playground/issues/4 through https://github.com/src-d/gitbase-playground/pull/16
>_ FE: a `package.json` \w standard scripts that do `echo 1`_
so every other thigs seems to be completed.
