### ISSUE TITLE
Define the help contents

### ISSUE THREAD

**Issue by carlosms** [src-d/gitbase-playground#103]
The current design spec includes a 'help' button, but we still need to define:

- Behavior. Will this be a modal window? a tooltip? an external link?
- Contents.

Related to #44.

**Comment by bzz** [comment]
Tagging @src-d/product here for feedback

**Comment by bzz** [comment]
Ok, so the consensus is - it will be a link, pointing to https://docs.sourced.tech/gitbase 🎉
