### ISSUE TITLE
SQL input box is broken in FF

### ISSUE THREAD

**Issue by smacker** [src-d/gitbase-playground#120]
1. If the height of the box isn't too big I can't scroll down to see the last line of the default query
2. Selection works weird:
<img width="753" alt="screen shot 2018-06-20 at 17 39 00" src="https://user-images.githubusercontent.com/406916/41669057-24bb6230-74b1-11e8-89e3-c7d65f334346.png">

**Comment by carlosms** [comment]
More info: works fine for chrome and firefox 60.0.2 on linux.
