### ISSUE TITLE
Code modal: languages improvements

### ISSUE THREAD

**Issue by smacker** [src-d/gitbase-playground#130]
- implement workarounds for java/bash/??? (languageMode != language for them) similar to the one in the dashboard
- currently, we highlight only 6 languages which bblfsh knows. We can add more. Or not. @bzz @marnovo

**Comment by carlosms** [comment]
Could you please explain a bit more the problem with java & bash? Thank you.

About the second point, both options make sense, but my preference would be to use the supported ones only.
While it's cool that the code viewer has the option to do syntax highlight for many more languages, if we have more than the ones bblfshd supports we would have a group of languages that will enable the UAST button, and others that won't. From the user's point of view It may be confusing. And we are assuming that most of the time you will have to set the language manually, so a big list will be less convenient.

**Comment by smacker** [comment]
> Could you please explain a bit more the problem with java & bash?

to make highlighting work for that languages we need mapping to special code-mirror modes: https://github.com/bblfsh/dashboard/blob/master/src/drivers.js#L12

**Comment by bzz** [comment]
As discussed today, let's proceed adding internal mapping to normalize language names, so all beta languages work: highlighted and UAST extraction.

**Comment by smacker** [comment]
I implemented the mapping in the lib: https://github.com/bblfsh/uast-viewer/pull/29

Need to merge & release and start using here.
