### ISSUE TITLE
Code->Uast Experience

### ISSUE THREAD

**Issue by bzz** [src-d/gitbase-playground#137]
1. On interaction between code-uast: is there a chance that we have off-by-one error when choosing a character under cursor?

<img width="852" alt="screen shot 2018-06-26 at 10 10 01 am" src="https://user-images.githubusercontent.com/5582506/41898033-35117e72-7929-11e8-858c-b996bbcf3a3c.png">

2. When clicking on the UAST, only cursor moves to the position in code, but not the scroll of the code panel - sometimes it is quite had to follow, especially on the filtered UASTs.
And click on UAST node does not scroll the code either.

3. Clicking on UAST node *hides( the code selection(cursor) for some reason. 
And to get it back, one needs to move mouse to hover over same UAST node again.

4. Manual resizing of UAST panel results in a strange "white box" artefact on the left.
Resizing back removes it.
<img width="996" alt="screen shot 2018-06-26 at 10 16 50 am" src="https://user-images.githubusercontent.com/5582506/41898467-6971bf50-792a-11e8-8989-2276e28a56ff.png">

**Comment by smacker** [comment]
1. bblfsh bug. Similar to https://github.com/bblfsh/dashboard/issues/68 You can see it works correctly for java.
2. this isn't implemented. Let's file a feature request to bblfsh dashboard?
3. didn't really get what you mean
4. Can't reproduce. Could you please provide steps?

**Comment by bzz** [comment]
> 1.

Do you mean that it's the same as https://github.com/bblfsh/documentation/issues/130 ?

> 2. this isn't implemented. Let's file a feature request to bblfsh dashboard?

👍 though, dashboard or uast-viewer?

> 3. didn't really get what you mean

Steps to reproduce
 - open Code-> UAST
 - hover UAST node (see it get focus \w cursor)
 - click on same UAST node (see cursor disappear) 
    Much more intuitive would be keep Code highlight (and scroll to it)

> 4. Can't reproduce. Could you please provide steps?

 - query with code 
 - Code -> UAST
 - resize UAST panel to make it bigger by dragging 3 ellipses

**Comment by bzz** [comment]
> 1. When drivers start returning consistent position

makes sense, so far - the only tracking point of this from LA seems to be bblfsh/documentation#130  - so waiting for new release and update then

> 2. uast-viewer isn't a product of src-d. Dashboard is. 

Sounds good, https://github.com/bblfsh/dashboard/issues/136

> 3.  It happens only when highlighting is a cursor, not a selection

👍 
https://github.com/bblfsh/uast-viewer/issues/28

4. I will test on latest staging again as soon as released and re-open if needed
