### ISSUE TITLE
Drone does not push new releases on new tag

### ISSUE THREAD

**Issue by carlosms** [src-d/gitbase-playground#139]
The last `v0.0.7` tag did not trigger a build in drone.
There must be something wrong in our `.drone.yml` file.

cc @rporres.

edit: by "cc" I mean if you can spare some time to take a quick look, your help is greatly appreciated, as always, @rporres :)

**Comment by carlosms** [comment]
There was no bug, somehow we simply forgot to turn on drone's "Tag Hooks".

**Comment by rporres** [comment]
My bad then. I didn't turn it on as there was no need since we didn't want to do anything on push at the time

**Comment by carlosms** [comment]
No problem, the fault is also on us because we should have tested with a new release as soon as we moved to drone
