### ISSUE TITLE
Missing language name for TypeScript

### ISSUE THREAD

**Issue by carlosms** [src-d/gitbase-playground#146]
The TypeScript language does not have a name in the languages dropdown.

The `/get-languages` response does not contain `name`. In this case we should probably use the `id`.

```
    {  
      "id":"javascript",
      "name":"JavaScript"
    },
    {  
      "id":"typescript",
      "name":""
    },
```

**Comment by smacker** [comment]
why do we have typescript on staging at all? it's alpha language: https://doc.bblf.sh/languages.html

**Comment by smacker** [comment]
I don't think we should fix it on our side. v0.2 that is installed is very old and doesn't support new sdk. 
Name was introduced only here: https://github.com/bblfsh/typescript-driver/commit/662c22420cd588277de11c9c03a5dd64a0d4e098#diff-254f3fc70c18f8f3ef548aabd28df762
But there is no release with this changes.

**Comment by carlosms** [comment]
It is in staging for no special reason, it was in the default list of drivers [here](https://github.com/src-d/charts/blob/master/gitbase-playground/values.yaml#L46) and we copied it to our `.helm-staging.yml`.
I agree with leaving only drivers in beta.
