### ISSUE TITLE
dep ensure in back-dependencies

### ISSUE THREAD

**Issue by smacker** [src-d/gitbase-playground#160]
Do we need it? Or we can we remove it?
We vendor all dependencies, so it isn't necessary to run `dep`. Do I miss some use case?

**Comment by bzz** [comment]
AFAICS  [back-dependencies](https://github.com/src-d/gitbase-playground/blob/master/Makefile#L95) runs only [dep ensure](https://golang.github.io/dep/docs/daily-dep.html#basics)  and is used only in `dependencies` and `validate-commit`.

At least for dev workflow, I see a value in `make dependencies` in the case of a new lib added to the backend as it takes care of a new dependency, and make sure it's included in `.toml`.

**Comment by smacker** [comment]
@bzz could you please provide a particular use case?

For now, I see that our deps are vendored so `dep ensure` must do nothing. If it changes anything it's wrong. And to check that we vendored our deps correctly we have `validate-commit`.

**Comment by carlosms** [comment]
Closing, it was removed in #205.
