### ISSUE TITLE
Vertical alignment of tooltip text

### ISSUE THREAD

**Issue by carlosms** [src-d/gitbase-playground#166]
Requested by @ricardobaeta here https://github.com/src-d/gitbase-playground/pull/159#issuecomment-401535749:

> Just a minor detail, about the vertical alignment of the query text. I would love for it to vertical align center with the height of the tooltip.
> 
> ![image](https://user-images.githubusercontent.com/1746146/42124871-c4fdd21a-7c62-11e8-9d99-d9f098d8cc66.png)
>

**Comment by ricardobaeta** [comment]
✨
