### ISSUE TITLE
Add Integration Test to CI to check presence of FOOTER_HTML

### ISSUE THREAD

**Issue by bzz** [src-d/gitbase-playground#173]
Add curl to CI to check HTML snippet was added by https://github.com/src-d/gitbase-playground/issues/165

As discussed elsewhere: `curl` + `grep` should be enough for this case.

**Comment by carlosms** [comment]
Maybe someone can help me out.

I tried to do a test in my fork:
https://github.com/carlosms/gitbase-playground/commit/ad2f4908e9d56ba29c9dcd0ef73751315f0c2e96

But I don't see the reason why it works locally but fails in Travis:
https://travis-ci.org/carlosms/gitbase-playground/jobs/399583173#L965

Any ideas?

**Comment by smacker** [comment]
As suggested in slack removing last slash helped:
https://github.com/src-d/gitbase-playground/pull/177
https://travis-ci.org/src-d/gitbase-playground/jobs/399935192

**Comment by carlosms** [comment]
After doing some more testing, the test always fails for my fork. But a custom trigger with the same travis conf in this project master works with slashes, localhost, 127.0.0.1...
https://travis-ci.org/src-d/gitbase-playground/builds/399945172
