### ISSUE TITLE
Sometimes query fails with no error message

### ISSUE THREAD

**Issue by carlosms** [src-d/gitbase-playground#176]
Sometimes the a query returns `502` and the interface reports `Query Failed - {}`.

**Comment by smacker** [comment]
what should be fixed here? The error message?

**Comment by carlosms** [comment]
Yes, the error message should be more descriptive than `{}`.

Then, unrelated to the error reporting, the other thing that we might want to look into is why. Is this probably a timeout waiting for the gitbase reply? If that's the case we might want to increase it, or make it configurable... Any thoughts on this?

**Comment by smacker** [comment]
If you are talking about staging, as I mentioned on slack before there is some kind of proxy with 30s timeout. I have no idea where the app is deployed. But if we assume on google then there is timeout on load balancers https://cloud.google.com/load-balancing/docs/backend-service

**Comment by smacker** [comment]
Currently, on staging in case of 502 I get this:
<img width="259" alt="screen shot 2018-07-04 at 17 03 24" src="https://user-images.githubusercontent.com/406916/42284255-3b874f78-7fac-11e8-9a80-16e265ae7afc.png">

**Comment by smacker** [comment]
Ah. Okay. Only Chrome related issue. It works fine in FF.
