### ISSUE TITLE
Version endpoint should include versions of dependencies

### ISSUE THREAD

**Issue by bzz** [src-d/gitbase-playground#184]
Right now we only display version of the gibase-playground build.

This issue is about adding 2 extra fields:
 - bblfsh version
 - gitbase version

in the output of the `curl <host>/version`

**Comment by carlosms** [comment]
gitbase has a version command, but that's not really accessible to us, we only have the DB connection endpoint.

Should we open a request for them to implement [`VERSION`](https://dev.mysql.com/doc/refman/8.0/en/information-functions.html#function_version)?

**Comment by smacker** [comment]
VERSION function is implemented in gitbase master. Let's wait for new release?

**Comment by carlosms** [comment]
Or we could implement it now against master, reporting the version as unknown if `VERSION` is not available.

Are we going to include this information in the interface somewhere, similar to bblfsh dashboard?

**Comment by bzz** [comment]
@carlosms for now, let's include it in only in `/version` endpoint results

>  reporting the version as unknown if VERSION is not available.

sounds good!
