### ISSUE TITLE
Results tab disappears if query fails

### ISSUE THREAD

**Issue by bzz** [src-d/gitbase-playground#185]
Right now, if a new query fails after some time of execution (~30sec) - error message is shown, but the tab disappear 😕 

That is inconsistent with the rest of the tab behaviour. To be consistent, we should keep the tab open, it should have empty results and an some kind of "error" state of a "broken robot".

@ricardobaeta what do you think?

Example of the query that fails slow in details below.
<details>

```sql
SELECT files.repository_id, files.file_path,
 ARRAY_LENGTH(UAST(
   files.blob_content,
   LANGUAGE(files.file_path, files.blob_content),
   '//*[@roleFunction and @roleDeclaration]'
 )) as functions
FROM files
NATURAL JOIN refs
WHERE 
LANGUAGE(files.file_path,files.blob_content) = 'Go'
AND refs.ref_name = 'HEAD'
ORDER BY functions
```
</details>

**Comment by ricardobaeta** [comment]
Hi @bzz and @carlosms 

You can find the Query Error Tab animation in the same folder as the other project's assets.

[Query Error Tab Animation](https://drive.google.com/file/d/1pxISPPkfNyBgZHpKe7NsZz4_hpN_LF0x/view?usp=sharing)

**Comment by smacker** [comment]
@carlosms there is no much problem with restarting the animation. Something like this would work if you want to keep the same element: https://jsfiddle.net/ko4stxwf/4/

But with react you most probably can create new instance of img and it should work fine (most probably, I didn't test)
