### ISSUE TITLE
When stopping a query, kill the query in gitbase server

### ISSUE THREAD

**Issue by eiso** [src-d/gitbase-playground#199]
When stopping the execution of a query by pressing (x) in the UI, we should be able to kill that query on the server side. Right now, it seems that query will continue to execute. This probably requires an issue in the server project as well.

**Comment by carlosms** [comment]
Note: the mysql driver we use supports cancellation https://github.com/go-sql-driver/mysql#contextcontext-support

**Comment by eiso** [comment]
@bzz want to see if we can increase priority on this a bit. 

**Rationale:** Both Francesc and I often give demos using the playground, which means we're live writing queries and quite often we need to stop them, which means either letting them run (taking up all of our CPU) slowing down the other queries we write or killing the server and then starting again (which looks bad in a demo).

**Comment by bzz** [comment]
As it is supported on gitbase - let's do it! 

@ricardobaeta would you be able to incorporate an interface for this?

**Comment by ricardobaeta** [comment]
Sure @bzz 

![image](https://user-images.githubusercontent.com/1746146/44094615-9060d5b8-9fce-11e8-860b-5c036ccdf7ba.png)

> This is updated in Zeplin

**Comment by eiso** [comment]
And just to clarify, then "Cancel" & "(x)"  (on the tab label) would both kill the query.
