### ISSUE TITLE
Wrong local docker image tag in Travis tests

### ISSUE THREAD

**Issue by carlosms** [src-d/gitbase-playground#202]
After we merged https://github.com/src-d/ci/pull/82, the local docker image is tagged with `$(DEV_PREFIX)-$(COMMIT)$(GIT_DIRTY)` or `TRAVIS_TAG`.

In [travis.yml](https://github.com/src-d/gitbase-playground/blob/master/.travis.yml#L61) we still use the docker image `srcd/gitbase-playground:$TRAVIS_BRANCH`, and builds fail.

**Comment by bzz** [comment]
Thank you for prompt fixes!
