### ISSUE TITLE
Server INFO logging

### ISSUE THREAD

**Issue by eiso** [src-d/gitbase-playground#208]
When I start the gitbase playground from its docker image:

```
docker run -it \
    --name gitbase-playground \
    --network host \
    --env GITBASEPG_DB_CONNECTION="root@tcp(127.0.0.1:3306)/none" \
    --env GITBASEPG_SELECT_LIMIT=0 \
    srcd/gitbase-playground:latest
```

It would be great to have some [INFO] logging that shows the server is started. Right now it's just blank. See gitbase or bblfsh for nice examples. It would be especially great to see if it correctly discovered/connected to Gitbase & Bblfsh

**Comment by smacker** [comment]
Actually, we have such a log. But default log level is `warn`. You can override it using `ENV=dev` environmental variable.

**Comment by eiso** [comment]
Then edit my suggestion to having the default "WARN" include starting server logging with connection warnings if bblfh / gitbase does not connect.

**Comment by bzz** [comment]
> Knowing that your server has started and correctly connected to its expected components

let's change to include this information in the default logging level
