### ISSUE TITLE
Do not autorun sample queries

### ISSUE THREAD

**Issue by eiso** [src-d/gitbase-playground#209]
I would disable the autorun on sample queries and instead, have it just populate the query field. 

**Rationale:** often you want to edit the query before running it or just to see the query for inspiration

**Comment by carlosms** [comment]
pinging @ricardobaeta for UX suggestions

**Comment by ricardobaeta** [comment]
I understand the rationale, and I agree. Although, it sparkles another idea in my mind: when you click on a sample query, it opens a new tab, but if we're not going to run it, does it makes sense if I click on other example query to just update the query on that tab that didn't run, or open a new tab?

**Comment by bzz** [comment]
👍 Nice suggestion, totally agree, we even discussed that with @ricardobaeta couple of times at the beginning.
