### ISSUE TITLE
Avoid mounting /var/lib/bblfsh on docker-compose

### ISSUE THREAD

**Issue by smola** [src-d/gitbase-playground#211]
From @dennwc ([more](https://gist.github.com/dennwc/fc869156bc622c788fbc4bd39baf99dc)):

> Before running the compose file I decided to check what it does (because I don't trust random scripts). I don't like that it tries to mount /var/lib/bblfshd by default. Docker compose will keep containers, so I'm not sure why it needs a persistant directory in my FS by default. Removed the mount from the config.

Either relying on the container itself or using a named volume (which is managed by docker-compose itself) could make sense, since it is isolated and less likely to cause problems with the user setup. What do you think?

**Comment by smacker** [comment]
we don't mount `/var/lib/bblfsh` on host machine but inside docker.

It allows to reuse drivers after `docker-compose down`. At least for me super common solution when anything goes wrong.
For example I often have problems with bblfsh related to socket or `context deadline exceeded`.
`down` solves this problems and with mounted volumes (inside docker) next `up` is very quick.

**Comment by smola** [comment]
So it is already a named volume. Closing as invalid.
