### ISSUE TITLE
Backend: Rethink how to work with assets, bindata...

### ISSUE THREAD

**Issue by dpordomingo** [src-d/gitbase-playground#24]
from https://github.com/src-d/gitbase-playground/pull/15#discussion_r186789669 @smacker suggested that it would be great to:
> _[...] re-think how we work with assets. Maybe we can find better solution._

**Comment by smacker** [comment]
reasoning: my solution from code-annotation works, but it looks like a hack.

**Comment by carlosms** [comment]
Maybe we could do the following:
- remove `asset.go` from the repository, add it to `.gitignore`
- add a new `static_files_dev.go` that does not require `assets.go` and just returns 404
- control when we use `static_files_dev.go` and `static_files.go` with build tags
- `make build` takes care of building the frontend, runing `go-bindata`, and use the right flags in `go build`

With our current repo you can't clone and serve the frontend. To make the current `asset.go`  work you need to run `make front-build` first. So this solution is not that much different, you still need to run a `make` command before the app is usable.

**Comment by smacker** [comment]
I like the idea of build tags.
