### ISSUE TITLE
Show UAST from code

### ISSUE THREAD

**Issue by carlosms** [src-d/gitbase-playground#48]
The details need to worked out, but the code viewer (#47) should be able to provide the UAST from the code, using the `/parse` endpoint (#46).

**Comment by bzz** [comment]
The designs were updated in https://github.com/src-d/product/issues/264#issuecomment-398154008

**Comment by carlosms** [comment]
This is a summary of the current understanding from IRL conversations, still open to more discussion and feedback from product team:

When you click on the table row 'CODE' button the code viewer modal opens.
At this moment the frontend calls `/detect-lang`.
- As a first iteration we will use the blob contents only.
- As an improvement, If the row contains the file name with the default column name, we may use it too. e.g. `file_name`, `tree_entry_name`.

Besides the automatic detection the modal will offer a drop-down with a list of languages, similar to the one in http://dashboard.bblf.sh/. If the language detection fails we should inform the user of the possibility to select a language manually.
If a language was detected this drop-down will be also enabled, indicating which language was automatically detected.

If a language is detected or selected, it will enable:
- Syntax highlighting
- The 'UAST' button in the top menu of the modal window.

Clicking on 'UAST' will open the right panel, possibly showing some kind of 'loading' message or animation.
The frontend will call `/parse` with the currently selected language, and fill the right panel with the UAST or error message.

**Comment by carlosms** [comment]
Current status after the merge of #119.
Copied from https://github.com/src-d/gitbase-playground/pull/119#issuecomment-399035869:

Next steps:
1) show uast button is located in left pane not in the title of modal
2) there is no top bar on UAST (with locations, server, query) yet (#127).
3) bblfsh integration improvements (#123)
 - it doesn't return underlying error from bblfsh
 - list of languages is hard-coded
4) languages improvements
 - there are no workarounds for java/bash/??? yet (languageMode != language for them)
 - currently, we highlight only 6 languages which bblfsh knows. We can add more. Or not. 
5) frontend performance improvements

**Comment by carlosms** [comment]
Most of the work is already in master.

@smacker do you have any comments about "frontend performance improvements"? Is it performing worse here than in the bblfsh dashboard? Are there any optimizations we can try?

**Comment by smacker** [comment]
actually, it performs better for me now 😅  😅  😅

**Comment by carlosms** [comment]
great! Then let's close this one and open new issues if we find any problems/improvements.
