### ISSUE TITLE
Update build, for a single binary to include all fronted

### ISSUE THREAD

**Issue by bzz** [src-d/gitbase-playground#5]
Use the same approach as in [CAT](https://github.com/src-d/code-annotation): 
 - [x] release is a single binary
 - [x] every PR does not include re-generated JS but go-bindata proxies instead 
 - [x] is not `go get`able

**Comment by dpordomingo** [comment]
I think this issue would be solved by https://github.com/src-d/gitbase-playground/pull/15, at least the two first subtasks.

About the third one: 
>_is not `go get` able_

I do not understand it. Any idea @bzz ?

**Comment by bzz** [comment]
I think it stands for the way we build assets.go and will be full filled by that single PR as well.

It would be nice going futherther though to structure PRs to be smaller and address only 1 issue at the time

**Comment by dpordomingo** [comment]
Now that https://github.com/src-d/gitbase-playground/pull/15 has been merged, this requirements seems to be addressed; feel free to reopen if I missed something :face_with_head_bandage:

**Comment by dpordomingo** [comment]
I'll use this issue to connect @carlosms work with the frontend with the build system, so I'll work on top of its last PR https://github.com/src-d/gitbase-playground/pull/26

**Comment by bzz** [comment]
@dpordomingo nice! Thank you for update and prompt fix.

I think it's totally fine to include it in scope of the upcoming alpha1 release
