### ISSUE TITLE
Improve code detection and guess a language

### ISSUE THREAD

**Issue by smacker** [src-d/gitbase-playground#61]
A language should be guessed using enry.

I propose to add information which column is a code and language in `meta` of the query endpoint response.

**Comment by carlosms** [comment]
> I propose to add information which column is a code and language in meta of the query endpoint response.

Can you develop a bit more your idea? The current response `meta` contains information for the whole table, but the language is unique to each row.

e.g. in `select * from files` the column `blob_content` will not have a code button for binary files (like a `.png`), and each file may have a different language.

**Comment by smacker** [comment]
The original idea was to figure out which column is a code and add it to a response and return array of languages for each row. Though now we decided to detect language using separate endpoint and call it only when a user opens a modal window. I'm not sure how to handle binary files.

**Comment by smacker** [comment]
We do guess code & language now.
It's far from perfect but good enough for the current scope.
I'm closing the issue. Please create a new one if you see any particular cases that are needed to be improved.
