### ISSUE TITLE
Invalidate cache between releases

### ISSUE THREAD

**Issue by carlosms** [src-d/gitbase-playground#70]
Otherwise when a new release is deployed users have to hard-refresh the browser to see the changes.

**Comment by bzz** [comment]
Logging relevant discussion that happened elsewhere:
<img width="971" alt="screen shot 2018-06-13 at 5 34 16 pm" src="https://user-images.githubusercontent.com/5582506/41361734-0dd1502e-6f30-11e8-98bd-cb8dc9940736.png">
