### ISSUE TITLE
Edit tab titles

### ISSUE THREAD

**Issue by carlosms** [src-d/gitbase-playground#72]
Each tab should have an edit button that will allow to edit the displayed tab title.

**Comment by smacker** [comment]
should the title be replaced by input on this button click or it should be a modal dialog?

**Comment by carlosms** [comment]
This will be better answered by @ricardobaeta.
I think it makes sense to replace the current title with an input. Pressing enter or clicking outside of the input would confirm the new name, and pressing escape would cancel the edit.

**Comment by smacker** [comment]
@ricardobaeta please provide your input here. I also think it's better to replace the current title with an input but I would like to hear a confirmation from you.

**Comment by ricardobaeta** [comment]
@carlosms @smacker It makes sense yes. You have my ok.
