### ISSUE TITLE
Define the example queries

### ISSUE THREAD

**Issue by carlosms** [src-d/gitbase-playground#76]
The left bar contains placeholder examples that need to be defined

**Comment by bzz** [comment]
@smola @marnovo - we need query examples that are going to be part of "Sample queries" on the left of https://gitbase-playground-staging.srcd.run/

**Comment by smola** [comment]
Looking at https://gist.github.com/smola/c5a190856eaa580bfcde372aeff2cb7f (which are outdated), I would suggest the following.

Note that all of these need adapting to the new syntax and schema (cc @ajnavarro), maybe you already have some of these in your tests / regression tests?

## Get last commit message for every repository

```sql
SELECT c.message
FROM
    refs r
    JOIN commits c ON r.hash = c.hash
WHERE
    r.name = 'HEAD';
```

### Get top repositories by number of commits in HEAD:

```sql
SELECT
    repository_id,
    commit_count
FROM (
    SELECT
        r.repository_id,
        count(*) AS commit_count
    FROM
        refs r
        JOIN commits c ON history_idx(r.hash, c.hash) >= 0
     WHERE
        r.name = 'HEAD'
    GROUP BY r.repository_id
) AS q
ORDER BY commit_count DESC
LIMIT 10;
```

## Top languages by repository count

```sql
SELECT *
FROM (
    SELECT
        language,
        COUNT(repository_id) AS repository_count
    FROM (
        SELECT DISTINCT
            r.repository_id AS repository_id,
            language(t.name, b.content) AS language
        FROM
            refs r
            JOIN commits c ON r.hash = c.hash
            JOIN tree_entries t ON commit_has_tree(c.hash, t.tree_hash)
            JOIN blobs b ON t.entry_hash = b.hash
        WHERE
            r.name = 'HEAD'
    ) AS q1
    GROUP BY language
) AS q2
ORDER BY repository_count DESC;
```

## Others

We would need the first query to be one that returns blobs and UAST for a given language. This way it could be showcases easily. I would suggest somehint like: _select all path, contents and uast for files named main.go_.

**Comment by marnovo** [comment]
I'd also add:

```SQL
SELECT COUNT(*) as num_commits, month, repo_id, committer_email
FROM (
    SELECT
        MONTH(committer_when) as month,
        r.repository_id as repo_id,
        committer_email
    FROM ref_commits r
    INNER JOIN commits c 
            ON YEAR(c.committer_when) = 2018 AND r.commit_hash = c.commit_hash
    WHERE r.ref_name = 'HEAD'
) as t
GROUP BY committer_email, month, repo_id
```

**Comment by bzz** [comment]
@carlosms @smacker as discussed, let's proceed and add those initial ones that are listed here
