### ISSUE TITLE
Wrong behaviour tab title edits

### ISSUE THREAD

**Issue by carlosms** [src-d/gitbase-playground#97]
- When the pencil icon is clicked the new textarea does not get focused automatically. This is confusing because you start writing and nothing happens
- If you click on more than one pencil icons, you can have a few tab titles as textarea. I think this could be related to the previous point, if the textarea does not get focused the event on focus lost does not get fired.
- There space key does not work
- The arrow keys (or ctrl+arrow) do not move the cursor, they change between tabs

**Comment by smacker** [comment]
everything was fixed
